version: '3.8'

services:
 
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: sic_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: root
      DB_USER: root
      DB_PASSWORD: root
      DB_SSL: "false"
      NODE_ENV: production
    depends_on:
      - postgres
    networks:
      - sic_network
  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    container_name: sic_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"  
    environment:
      VITE_API_URL: http://localhost:3000/api
      VITE_BACKEND_URL: http://localhost:3000
    depends_on:
      - backend
    networks:
      - sic_network

  postgres:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - sic_network

networks:
  sic_network:
    driver: bridge
    name: sic_network


volumes:
  app_data:
    driver: local