version: '3.8'

services:
 
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: sic_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: 127.0.0.1  # Aqu√≠ se coloca la URL del docker compose de la base de datos o la propia imagen de la base de datos que se use
      DB_PORT: 5432
      DB_NAME: SIC_PROYECTO
      DB_USER: root
      DB_PASSWORD: root
      PORT: 3000
      NODE_ENV: development
      FRONTEND_URL: http://localhost:5173
    volumes:
      - ./BE:/app
      - /app/node_modules
   
    network_mode: host
    

  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    container_name: sic_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000/api
      VITE_BACKEND_URL: http://localhost:3000
    volumes:
      - ./FE:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - sic_network
networks:
  sic_network:
    driver: bridge
    name: sic_network